// ============================================
// English IATA codes
// ============================================
export const iataToCityName: Record<string, string> = {
  "DXB": "Dubai",
  "JFK": "New York",
  "LHR": "London",
  "RUH": "Riyadh",
  "JED": "Jeddah",
  "CAI": "Cairo",
  "IST": "Istanbul",
  "CDG": "Paris",
  "NRT": "Tokyo",
  "LAX": "Los Angeles",
  "SFO": "San Francisco",
  "ORD": "Chicago",
  "ATL": "Atlanta",
  "MIA": "Miami",
  "BOS": "Boston",
  "DCA": "Washington",
  "IAD": "Washington",
  "YUL": "Montreal",
  "YYZ": "Toronto",
  "SYD": "Sydney",
  "MEL": "Melbourne",
  "BKK": "Bangkok",
  "SIN": "Singapore",
  "KUL": "Kuala Lumpur",
  "HKG": "Hong Kong",
  "ICN": "Seoul",
  "PEK": "Beijing",
  "PVG": "Shanghai",
  "BOM": "Mumbai",
  "DEL": "Delhi",
  "AMM": "Amman",
  "BEY": "Beirut",
  "DOH": "Doha",
  "AUH": "Abu Dhabi",
  "BAH": "Bahrain",
  "KWI": "Kuwait",
  "MCT": "Muscat",
  "CMN": "Casablanca",
  "TUN": "Tunis",
  "ALG": "Algiers",
  "SSH": "Sharm El Sheikh",
  "HRG": "Hurghada",
  "LXR": "Luxor",
  "ASW": "Aswan",
  "TBS": "Tbilisi",
  "EVN": "Yerevan",
  "BAK": "Baku",
  "KTM": "Kathmandu",
  "MLE": "Male",
  "CMB": "Colombo",
  "CGK": "Jakarta",
  "DPS": "Bali",
  "MNL": "Manila",
  "HAN": "Hanoi",
  "SGN": "Ho Chi Minh",
  "PNH": "Phnom Penh",
  "RGN": "Yangon",
  "VTE": "Vientiane",
  "LPQ": "Luang Prabang",
  "REP": "Siem Reap",
  "KOS": "Sihanoukville",
  "NYC": "New York",
  "WAS": "Washington",
  "CHI": "Chicago",
  "QSF": "San Francisco",
  "LON": "London",
  "PAR": "Paris",
  "ROM": "Rome",
  "MIL": "Milan",
  "MAD": "Madrid",
  "BCN": "Barcelona",
  "BER": "Berlin",
  "MUC": "Munich",
  "VIE": "Vienna",
  "AMS": "Amsterdam",
  "BRU": "Brussels",
  "ZUR": "Zurich",
  "GVA": "Geneva",
  "CPH": "Copenhagen",
  "OSL": "Oslo",
  "STO": "Stockholm",
  "HEL": "Helsinki",
  "PRG": "Prague",
  "BUD": "Budapest",
  "WAW": "Warsaw",
  "ATH": "Athens",
  "LIS": "Lisbon",
  "DUB": "Dublin",
  "EDI": "Edinburgh",
  "MAN": "Manchester",
  "BHX": "Birmingham",
  "GLA": "Glasgow",
  "NCL": "Newcastle",
  "LPL": "Liverpool",
  "BRS": "Bristol",
  "ARN": "Stockholm",
  "BMA": "Stockholm",
  "NYO": "Stockholm",
  "FRA": "Frankfurt",
  "HAM": "Hamburg",
  "CGN": "Cologne",
  "DUS": "Dusseldorf",
  "HBE": "Alexandria",
  "SAW": "Istanbul",
  "ESB": "Ankara",
  "IZM": "Izmir",
  "AYT": "Antalya",
  "ADB": "Izmir",
  "BGW": "Baghdad",
  "BSR": "Basra",
  "EBL": "Erbil",
  "NJF": "Najaf",
  "ISU": "Sulaymaniyah",
  "KSH": "Kermanshah",
  "AWZ": "Ahvaz",
  "IFN": "Isfahan",
  "MHD": "Mashhad",
  "SYZ": "Shiraz",
  "TBZ": "Tabriz",
  "IKA": "Tehran",
  "ZAH": "Zahedan",
  "KBL": "Kabul",
  "KDH": "Kandahar",
  "MUX": "Multan",
  "LYP": "Faisalabad",
  "SKT": "Sialkot",
  "PEW": "Peshawar",
  "ISB": "Islamabad",
  "LHE": "Lahore",
  "KHI": "Karachi",
  "DAC": "Dhaka",
  "CGP": "Chittagong",
  "PBH": "Thimphu",
  "GOI": "Goa",
  "HYD": "Hyderabad",
  "MAA": "Chennai",
  "BLR": "Bangalore",
  "CCU": "Kolkata",
  "AMD": "Ahmedabad",
  "COK": "Kochi",
  "TRV": "Thiruvananthapuram",
  "GAU": "Guwahati",
  "JAI": "Jaipur",
  "LKO": "Lucknow",
  "PAT": "Patna",
  "IXC": "Chandigarh",
  "IXE": "Mangalore",
  "IXR": "Ranchi",
  "IXZ": "Port Blair",
  "SXR": "Srinagar",
  "IXB": "Bagdogra",
  "IXM": "Madurai",
  "IXU": "Aurangabad",
  "NAG": "Nagpur",
  "PNQ": "Pune",
  "RPR": "Raipur",
  "VTZ": "Visakhapatnam",
  "BBI": "Bhubaneswar",
  "IXL": "Leh",
  "GOP": "Gorakhpur",
  "JDH": "Jodhpur",
  "UDR": "Udaipur",
  "ATQ": "Amritsar",
  "IXJ": "Jammu",
  "KUU": "Kullu",
  "SLV": "Shimla",
  "TIR": "Tirupati",
  "VGA": "Vijayawada",
  "IXA": "Agartala",
  "IMF": "Imphal",
  "SHL": "Shillong",
  "AJL": "Aizawl",
  "DIU": "Diu",
  "JGA": "Jamnagar",
  "RAJ": "Rajkot",
  "BHU": "Bhavnagar",
  "STV": "Surat",
  "BDQ": "Vadodara",
  "BHO": "Bhopal",
  "GWL": "Gwalior",
  "IDR": "Indore",
  "JLR": "Jabalpur",
  "KBH": "Khajuraho",
  "REW": "Rewa",
  "UJN": "Ujjain",
  "RJA": "Rajahmundry",
  "TCR": "Tuticorin",
  "TVM": "Trivandrum",
  "CNN": "Kannur",
  "CCJ": "Kozhikode",
  "SLL": "Salalah",
  "DMM": "Dammam",
  "ELQ": "Gassim",
  "AJF": "Jouf",
  "AJU": "Arar",
  "BGG": "Bisha",
  "DWD": "Dawadmi",
  "EAM": "Nejran",
  "GIZ": "Jazan",
  "HAS": "Hail",
  "HOF": "Hofuf",
  "MED": "Madinah",
  "NUM": "Neom",
  "RAE": "Arar",
  "RAH": "Rafha",
  "SHW": "Sharurah",
  "SLF": "Sulayel",
  "TIF": "Taif",
  "TUU": "Tabuk",
  "URY": "Gurayat",
  "WAE": "Wadi Ad Dawasir",
  "EJH": "Wedjh",
  "YNB": "Yanbu",
  "ZUL": "Zilfi",
  "TIA": "Tirana",
  "EVN": "Yerevan",
  "GRZ": "Graz",
  "INN": "Innsbruck",
  "KLU": "Klagenfurt",
  "LNZ": "Linz",
  "SZG": "Salzburg",
  "VIE": "Vienna",
  "GYD": "Baku",
  "MSQ": "Minsk",
  "BRU": "Brussels",
  "CRL": "Charleroi",
  "LGG": "Liege",
  "OST": "Ostend",
  "SJJ": "Sarajevo",
  "BOJ": "Bourgas",
  "SOF": "Sofia",
  "VAR": "Varna",
  "DBV": "Dubrovnik",
  "ZAG": "Zagreb",
  "LCA": "Larnaca",
  "PFO": "Paphos",
  "PRG": "Prague",
  "AAL": "Aalborg",
  "BLL": "Billund",
  "CPH": "Copenhagen",
  "FAE": "Faroe Islands",
  "MHQ": "Mariehamn",
  "TLL": "Tallinn",
  "HEL": "Helsinki",
  "OUL": "Oulu",
  "RVN": "Rovaniemi",
  "TMP": "Tampere",
  "TKU": "Turku",
  "VAA": "Vaasa",
  "AJA": "Ajaccio",
  "BIA": "Bastia",
  "EGC": "Bergerac",
  "BZR": "Beziers",
  "BIQ": "Biarritz",
  "BOD": "Bordeaux",
  "BES": "Brest",
  "CFR": "Caen",
  "CLY": "Calvi",
  "CMF": "Chambery",
  "CHR": "Chateauroux",
  "CFE": "Clermont-Ferrand",
  "DOL": "Deauville",
  "DNR": "Dinard",
  "FSC": "Figari",
  "GNB": "Grenoble",
  "LRH": "La Rochelle",
  "LIL": "Lille",
  "LIG": "Limoges",
  "LRT": "Lorient",
  "LYS": "Lyon",
  "MRS": "Marseille",
  "MPL": "Montpellier",
  "NTE": "Nantes",
  "NCE": "Nice",
  "FNI": "Nimes",
  "PAR": "Paris",
  "PUF": "Pau",
  "PGF": "Perpignan",
  "PIS": "Poitiers",
  "RNS": "Rennes",
  "RDZ": "Rodez",
  "EBU": "Saint Etienne",
  "SNR": "Saint Nazaire",
  "SXB": "Strasbourg",
  "TLN": "Toulon",
  "TLS": "Toulouse",
  "TUF": "Tours",
  "AHO": "Alghero",
  "AOI": "Ancona",
  "BRI": "Bari",
  "BGY": "Bergamo",
  "BLQ": "Bologna",
  "VBS": "Brescia",
  "BDS": "Brindisi",
  "CAG": "Cagliari",
  "CTA": "Catania",
  "CRV": "Crotone",
  "FLR": "Florence",
  "GOA": "Genoa",
  "SUF": "Lamezia Terme",
  "LMP": "Lampedusa",
  "LIN": "Milan",
  "NAP": "Naples",
  "OLB": "Olbia",
  "PMO": "Palermo",
  "PNL": "Pantelleria",
  "PSA": "Pisa",
  "REG": "Reggio Calabria",
  "RMI": "Rimini",
  "FCO": "Rome",
  "TQR": "San Domino",
  "TPS": "Trapani",
  "TRS": "Trieste",
  "TRN": "Turin",
  "VCE": "Venice",
  "VRN": "Verona",
  "FRL": "Forli",
  "GRO": "Girona",
  "IBZ": "Ibiza",
  "XRY": "Jerez",
  "MJV": "Murcia",
  "REU": "Reus",
  "SDR": "Santander",
  "SCQ": "Santiago",
  "SVQ": "Seville",
  "VLC": "Valencia",
  "VLL": "Valladolid",
  "VGO": "Vigo",
  "ZAZ": "Zaragoza",
  "SPC": "Santa Cruz",
  "TFN": "Tenerife",
  "TFS": "Tenerife",
  "LPA": "Gran Canaria",
  "FUE": "Fuerteventura",
  "ACE": "Lanzarote",
  "SMI": "Samos",
  "JMK": "Mykonos",
  "JTR": "Santorini",
  "RHO": "Rhodes",
  "CFU": "Corfu",
  "HER": "Heraklion",
  "CHQ": "Chania",
  "EFL": "Kefalonia",
  "ZTH": "Zakynthos",
  "JSI": "Skiathos",
  "KGS": "Kos",
  "MJT": "Mytilene",
  "PVK": "Preveza",
  "SKU": "Skiros",
  "JSH": "Sitia",
  "KVA": "Kavala",
  "AXD": "Alexandroupolis",
  "JKH": "Chios",
  "LXS": "Limnos",
  "MLO": "Milos",
  "JNX": "Naxos",
  "PAS": "Paros",
  "JTY": "Astypalaia",
  "KZI": "Kozani",
  "LRA": "Larissa",
  "PKH": "Porto Heli",
  "SPJ": "Sparta",
  "VOL": "Volos",
  "ZTH": "Zakynthos",
  "BZG": "Bydgoszcz",
  "GDN": "Gdansk",
  "KTW": "Katowice",
  "KRK": "Krakow",
  "LUZ": "Lublin",
  "LCJ": "Lodz",
  "POZ": "Poznan",
  "RZE": "Rzeszow",
  "SZZ": "Szczecin",
  "WAW": "Warsaw",
  "WRO": "Wroclaw",
  "OTP": "Bucharest",
  "CLJ": "Cluj",
  "CND": "Constanta",
  "IAS": "Iasi",
  "OMR": "Oradea",
  "SBZ": "Sibiu",
  "SCV": "Suceava",
  "TSR": "Timisoara",
  "TGM": "Targu Mures",
  "BCM": "Bacau",
  "CRA": "Craiova",
  "KIV": "Chisinau",
  "BEG": "Belgrade",
  "INI": "Nis",
  "TGD": "Podgorica",
  "TIV": "Tivat",
  "PRN": "Pristina",
  "SKP": "Skopje",
  "OHD": "Ohrid",
  "LJU": "Ljubljana",
  "MBX": "Maribor",
  "POW": "Portoroz",
  "BTS": "Bratislava",
  "KSC": "Kosice",
  "PZY": "Piestany",
  "SLD": "Sliac",
  "TAT": "Poprad",
  "BZG": "Bydgoszcz",
  "RZE": "Rzeszow",
  "SZZ": "Szczecin",
  "LUZ": "Lublin",
  "LCJ": "Lodz",
  "POZ": "Poznan",
  "WRO": "Wroclaw",
  "KTW": "Katowice",
  "GDN": "Gdansk",
  "KRK": "Krakow",
  "WAW": "Warsaw",
  "BZG": "Bydgoszcz",
};

// ============================================
// Arabic city names → IATA
// ============================================
const arabicToIata: Record<string, string> = {
  // 🇦🇪 الإمارات
  "دبي": "DXB",
  "dubai": "DXB",
  " dubai": "DXB",
  "أبوظبي": "AUH",
  "ابوظبي": "AUH",
  "abu dhabi": "AUH",
  "الشارقة": "SHJ",
  "شارقة": "SHJ",
  "sharjah": "SHJ",
  "العين": "AAN",
  "عين": "AAN",
  "al ain": "AAN",
  "رأس الخيمة": "RKT",
  "راس الخيمة": "RKT",
  "ras al khaimah": "RKT",
  "الفجيرة": "FJR",
  "فجيرة": "FJR",
  "fujairah": "FJR",

  // 🇸🇦 السعودية
  "الرياض": "RUH",
  "riyadh": "RUH",
  "جدة": "JED",
  "jedda": "JED",
  "jeddah": "JED",
  "مكة": "JED",
  "المدينة": "MED",
  "المدينة المنورة": "MED",
  "madinah": "MED",
  "الدمام": "DMM",
  "دمام": "DMM",
  "dammam": "DMM",
  "الخبر": "DMM",
  "خبر": "DMM",
  "القطيف": "DMM",
  "الأحساء": "HOF",
  "الاحساء": "HOF",
  "حفر الباطن": "HOF",
  "حفر": "HOF",
  "hofuf": "HOF",
  "تبوك": "TUU",
  "tabuk": "TUU",
  "حائل": "HAS",
  "hail": "HAS",
  "أبها": "AHB",
  "ابها": "AHB",
  "abha": "AHB",
  "خميس مشيط": "AHB",
  "تيف": "TIF",
  "الطائف": "TIF",
  "طائف": "TIF",
  "taif": "TIF",
  "نجران": "EAM",
  "najran": "EAM",
  "جازان": "GIZ",
  "jazan": "GIZ",
  "ينبع": "YNB",
  "yanbu": "YNB",
  "عرعر": "RAE",
  "arar": "RAE",
  "القريات": "URY",
  "قريات": "URY",
  "gurayat": "URY",
  "سكاكا": "AJF",
  "سكاكا الجوف": "AJF",
  "jouf": "AJF",
  "الباحة": "AJF",
  "باحة": "AJF",
  "الوجه": "AJF",
  "وجه": "AJF",
  "ضبا": "AJF",
  "شرورة": "SHW",
  "sharurah": "SHW",
  "وادي الدواسر": "WAE",
  "wedjh": "EJH",
  "الوجه": "EJH",
  "وجه": "EJH",
  "القصيم": "ELQ",
  "قصيم": "ELQ",
  "بريدة": "ELQ",
  "بريدة القصيم": "ELQ",
  "عنيزة": "ELQ",
  "الرس": "ELQ",
  "الزلفي": "ZUL",
  "زلفي": "ZUL",
  "الرس": "ZUL",
  "الدوادمي": "DWD",
  "دوادمي": "DWD",
  "الخرج": "DWD",
  "خرج": "DWD",
  "السليل": "SLF",
  "سليل": "SLF",
  "بيشة": "BGG",
  "bisha": "BGG",
  "بلجرشي": "BGG",
  "المجاردة": "BGG",
  "نماص": "BGG",
  "محايل": "BGG",
  "رجال ألمع": "BGG",
  "ظهران الجنوب": "BGG",
  "النماص": "BGG",
  "بارق": "BGG",
  "الدرب": "BGG",
  "فرسان": "BGG",
  "أحد المسارحة": "BGG",
  "العارضة": "BGG",
  "صبيا": "BGG",
  "ضمد": "BGG",
  "الحرث": "BGG",
  "الريث": "BGG",
  "الطوال": "BGG",
  "جازان": "GIZ",
  "صامطة": "GIZ",
  "أبو عريش": "GIZ",
  "صبياء": "GIZ",
  "بيش": "GIZ",
  "الدائر": "GIZ",
  "الحرث": "GIZ",
  "العارضة": "GIZ",
  "فرسان": "GIZ",
  "هروب": "GIZ",
  "الدرب": "GIZ",
  "أحد المسارحة": "GIZ",
  "ضمد": "GIZ",
  "الريث": "GIZ",
  "الطوال": "GIZ",
  "الكدرة": "GIZ",
  "الشقيق": "GIZ",
  "الجرادية": "GIZ",
  "الموسم": "GIZ",
  "الحضن": "GIZ",
  "الخوبة": "GIZ",
  "الرديف": "GIZ",
  "القفل": "GIZ",
  "المضايا": "GIZ",
  "الشطيفية": "GIZ",
  "الحمي": "GIZ",
  "الشريعة": "GIZ",
  "العيدابي": "GIZ",
  "فيفا": "GIZ",
  "الطوال": "GIZ",
  "الريث": "GIZ",
  "ضمد": "GIZ",
  "صبيا": "GIZ",
  "أبو عريش": "GIZ",
  "صامطة": "GIZ",
  "الدائر": "GIZ",
  "الحرث": "GIZ",
  "العارضة": "GIZ",
  "فرسان": "GIZ",
  "هروب": "GIZ",
  "الدرب": "GIZ",
  "أحد المسارحة": "GIZ",
  "ضمد": "GIZ",
  "الريث": "GIZ",
  "الطوال": "GIZ",
  "الكدرة": "GIZ",
  "الشقيق": "GIZ",
  "الجرادية": "GIZ",
  "الموسم": "GIZ",
  "الحضن": "GIZ",
  "الخوبة": "GIZ",
  "الرديف": "GIZ",
  "القفل": "GIZ",
  "المضايا": "GIZ",
  "الشطيفية": "GIZ",
  "الحمي": "GIZ",
  "الشريعة": "GIZ",
  "العيدابي": "GIZ",
  "فيفا": "GIZ",
  "نوم": "NUM",
  "نيوم": "NUM",
  "neom": "NUM",

  // 🇪🇬 مصر
  "القاهرة": "CAI",
  "cairo": "CAI",
  "الاسكندرية": "HBE",
  "اسكندرية": "HBE",
  "alexandria": "HBE",
  "الإسكندرية": "HBE",
  "شرم الشيخ": "SSH",
  "sharm el sheikh": "SSH",
  "شرم": "SSH",
  "الغردقة": "HRG",
  "غردقة": "HRG",
  "hurghada": "HRG",
  "الأقصر": "LXR",
  "أقصر": "LXR",
  "luxor": "LXR",
  "أسوان": "ASW",
  "اسوان": "ASW",
  "aswan": "ASW",
  "مرسى علم": "RMF",
  "مرسي علم": "RMF",
  "marsa alam": "RMF",
  "طابا": "TCP",
  "taba": "TCP",
  "العريش": "AAC",
  "عريش": "AAC",
  "al arish": "AAC",
  "سوهاج": "HMB",
  "sohag": "HMB",
  "أسيوط": "ATZ",
  "اسيوط": "ATZ",
  "asyut": "ATZ",
  "قنا": "LXR",
  "قنا الأقصر": "LXR",
  "المنيا": "EMN",
  "منيا": "EMN",
  "minya": "EMN",
  "بورسعيد": "PSD",
  "بور سعيد": "PSD",
  "port said": "PSD",
  "الإسماعيلية": "ISI",
  "اسماعيلية": "ISI",
  "ismailia": "ISI",
  "السويس": "SUZ",
  "سويس": "SUZ",
  "suez": "SUZ",
  "دمياط": "DTI",
  "damietta": "DTI",
  "المنصورة": "MNF",
  "منصورة": "MNF",
  "mansoura": "MNF",
  "طنطا": "TTA",
  "tanta": "TTA",
  "كفر الشيخ": "KFS",
  "كفرالشيخ": "KFS",
  "kafr el sheikh": "KFS",
  "بني سويف": "EMN",
  "بنى سويف": "EMN",
  "beni suef": "EMN",
  "الفيوم": "EMN",
  "فيوم": "EMN",
  "fayoum": "EMN",
  "دمنهور": "DBA",
  "damanhour": "DBA",

  // 🇰🇼 الكويت
  "الكويت": "KWI",
  "kuwait": "KWI",
  "مدينة الكويت": "KWI",
  "الفروانية": "KWI",
  "فروانية": "KWI",
  "حولي": "KWI",
  "الأحمدي": "KWI",
  "الاحمدي": "KWI",
  "الجهراء": "KWI",
  "جهراء": "KWI",
  "مبارك الكبير": "KWI",

  // 🇧🇭 البحرين
  "البحرين": "BAH",
  "bahrain": "BAH",
  "المنامة": "BAH",
  "منامة": "BAH",
  "manama": "BAH",
  "المحرق": "BAH",
  "محرق": "BAH",
  "الرفاع": "BAH",
  "رفاع": "BAH",
  "مدينة عيسى": "BAH",
  "عيسى": "BAH",
  "مدينة حمد": "BAH",
  "حمد": "BAH",

  // 🇶🇦 قطر
  "قطر": "DOH",
  "الدوحة": "DOH",
  "doha": "DOH",
  "الدوحه": "DOH",
  "الخور": "DOH",
  "خور": "DOH",
  "الوكرة": "DOH",
  "وكرة": "DOH",
  "الريان": "DOH",
  "ريان": "DOH",
  "أم صلال": "DOH",
  "ام صلال": "DOH",

  // 🇴🇲 عمان
  "مسقط": "MCT",
  "muscat": "MCT",
  "مسقط": "MCT",
  "صلالة": "SLL",
  "salalah": "SLL",
  "صحار": "OHS",
  "sohar": "OHS",
  "نزوى": "OHS",
  "nizwa": "OHS",
  "صور": "OHS",
  "sur": "OHS",
  "خاصب": "OHS",
  "khasab": "OHS",
  "الرستاق": "OHS",
  "رستاق": "OHS",
  "عبري": "OHS",
  "ibri": "OHS",
  "بركاء": "OHS",
  "barka": "OHS",
  "السيب": "OHS",
  "سيب": "OHS",
  "seeb": "OHS",
  "بوشر": "OHS",
  "bawshar": "OHS",
  "مطرح": "OHS",
  "muttrah": "OHS",

  // 🇯🇴 الأردن
  "عمان": "AMM",
  "amman": "AMM",
  "العاصمة": "AMM",
  "الزرقاء": "AMM",
  "زرقاء": "AMM",
  "زرقا": "AMM",
  "إربد": "AMM",
  "اربد": "AMM",
  "irbid": "AMM",
  "السلط": "AMM",
  "سلط": "AMM",
  "salt": "AMM",
  "مادبا": "AMM",
  "madaba": "AMM",
  "جرش": "AMM",
  "jarash": "AMM",
  "عجلون": "AMM",
  "ajloun": "AMM",
  "الكرك": "AMM",
  "كرك": "AMM",
  "karak": "AMM",
  "الطفيلة": "AMM",
  "طفيلة": "AMM",
  "tafilah": "AMM",
  "معان": "AMM",
  "maan": "AMM",
  "العقبة": "AQJ",
  "عقبة": "AQJ",
  "aqaba": "AQJ",

  // 🇱🇧 لبنان
  "بيروت": "BEY",
  "beirut": "BEY",
  "طرابلس": "BEY",
  "tripoli": "BEY",
  "صيدا": "BEY",
  "sidon": "BEY",
  "صور": "BEY",
  "tyre": "BEY",
  "جبيل": "BEY",
  "byblos": "BEY",
  "زحلة": "BEY",
  "zahle": "BEY",

  // 🇮🇶 العراق
  "بغداد": "BGW",
  "baghdad": "BGW",
  "البصرة": "BSR",
  "بصرة": "BSR",
  "basra": "BSR",
  "أربيل": "EBL",
  "اربيل": "EBL",
  "erbil": "EBL",
  "السليمانية": "ISU",
  "سليمانية": "ISU",
  "sulaymaniyah": "ISU",
  "النجف": "NJF",
  "نجف": "NJF",
  "najaf": "NJF",
  "كربلاء": "BGW",
  "كربلاء المقدسة": "BGW",
  "karbala": "BGW",
  "الموصل": "BGW",
  "موصل": "BGW",
  "mosul": "BGW",
  "كركوك": "BGW",
  "kirkuk": "BGW",
  "دهوك": "EBL",
  "duhok": "EBL",

  // 🇸🇾 سوريا
  "دمشق": "DAM",
  "damascus": "DAM",
  "حلب": "ALP",
  "aleppo": "ALP",
  "اللاذقية": "LTK",
  "لاذقية": "LTK",
  "latakia": "LTK",
  "طرطوس": "LTK",
  "tartus": "LTK",
  "حمص": "DAM",
  "homs": "DAM",
  "حماة": "DAM",
  "hama": "DAM",

  // 🇵🇸 فلسطين
  "القدس": "JRS",
  "قدس": "JRS",
  "jerusalem": "JRS",
  "رام الله": "JRS",
  "رامالله": "JRS",
  "ramallah": "JRS",
  "بيت لحم": "JRS",
  "bethlehem": "JRS",
  "نابلس": "JRS",
  "nablus": "JRS",
  "غزة": "JRS",
  "gaza": "JRS",
  "الخليل": "JRS",
  "خليل": "JRS",
  "hebron": "JRS",
  "أريحا": "JRS",
  "اريحا": "JRS",
  "jericho": "JRS",
  "جنين": "JRS",
  "jenin": "JRS",

  // 🇾🇪 اليمن
  "صنعاء": "SAH",
  "sanaa": "SAH",
  "عدن": "ADE",
  "aden": "ADE",
  "المكلا": "RIY",
  "مكلا": "RIY",
  "mukalla": "RIY",
  "حضرموت": "RIY",
  "hadramaut": "RIY",
  "تعز": "TAI",
  "taiz": "TAI",
  "الحديدة": "HOD",
  "حديدة": "HOD",
  "hodeidah": "HOD",
  "إب": "IBB",
  "ibb": "IBB",
  "سيئون": "GXF",
  "seiyun": "GXF",
  "المهرة": "RIY",
  "مهرة": "RIY",
  "al mahrah": "RIY",

  // 🇱🇾 ليبيا
  "طرابلس": "TIP",
  "tripoli": "TIP",
  "بنغازي": "BEN",
  "بنغازى": "BEN",
  "benghazi": "BEN",
  "مصراتة": "MRA",
  "misrata": "MRA",
  "البيضاء": "LAQ",
  "بيضاء": "LAQ",
  "bayda": "LAQ",
  "سبها": "SEB",
  "sebha": "SEB",
  "درنة": "DRN",
  "derna": "DRN",

  // 🇹🇳 تونس
  "تونس": "TUN",
  "tunis": "TUN",
  "تونس العاصمة": "TUN",
  "سفاقس": "SFA",
  "sfax": "SFA",
  "سوسة": "TUN",
  "sousse": "TUN",
  "المنستير": "TUN",
  "منستير": "TUN",
  "monastir": "TUN",
  "القيروان": "TUN",
  "قيروان": "TUN",
  "kairouan": "TUN",
  "قابس": "TUN",
  "gabes": "TUN",
  "بنزرت": "TUN",
  "bizerte": "TUN",
  "نابل": "TUN",
  "nabeul": "TUN",
  "حمامات": "TUN",
  "hammamet": "TUN",
  "جربة": "DJE",
  "جربه": "DJE",
  "djerba": "DJE",
  "توزر": "TOE",
  "tozeur": "TOE",

  // 🇩🇿 الجزائر
  "الجزائر": "ALG",
  "algiers": "ALG",
  "وهران": "ORN",
  "wahran": "ORN",
  "oran": "ORN",
  "قسنطينة": "CZL",
  "constantine": "CZL",
  "عنابة": "AAE",
  "annaba": "AAE",
  "سطيف": "QSF",
  "setif": "QSF",
  "تيارت": "TID",
  "tiaret": "TID",
  "بسكرة": "BSK",
  "biskra": "BSK",
  "تلمسان": "TLM",
  "tlemcen": "TLM",
  "بشار": "CBH",
  "bechar": "CBH",
  "الأغواط": "LOO",
  "الاغواط": "LOO",
  "laghouat": "LOO",
  "الشلف": "CFK",
  "شلف": "CFK",
  "chlef": "CFK",
  "سعيدة": "BFW",
  "saïda": "BFW",
  "سكيكدة": "SKI",
  "skikda": "SKI",
  " Béjaïa": "BJA",
  "بجاية": "BJA",
  "bejaia": "BJA",
  "تيزي وزو": "BJA",
  "تيزي": "BJA",
  "tizi ouzou": "BJA",
  "المدية": "QSF",
  "مدية": "QSF",
  "medea": "QSF",
  "البليدة": "ALG",
  "بليدة": "ALG",
  "blida": "ALG",
  "بوعريريج": "QSF",
  "bouira": "QSF",
  "الطارف": "AAE",
  "طارف": "AAE",
  "tarf": "AAE",
  "قالمة": "QSF",
  "guelma": "QSF",
  "خنشلة": "QSF",
  "khenchela": "QSF",
  "سوق أهراس": "QSF",
  "souk ahras": "QSF",
  "تيبازة": "ALG",
  "tipaza": "ALG",
  "عين الدفلى": "ALG",
  "ain defla": "ALG",
  "النعامة": "CBH",
  "naama": "CBH",
  "عين تيموشنت": "TLM",
  "ain temouchent": "TLM",
  "غرداية": "GHA",
  "ghardaia": "GHA",
  "المنيعة": "GHA",
  "illizi": "VVZ",
  "الوادي": "ELU",
  "oued souf": "ELU",
  "الوادى": "ELU",
  "تقرت": "ELU",
  "touggourt": "ELU",
  "المسيلة": "QSF",
  "msila": "QSF",
  "الجلفة": "QSF",
  "djelfa": "QSF",
  "ميلة": "QSF",
  "mila": "QSF",
  "برج بوعريريج": "QSF",
  "bordj bou arreridj": "QSF",
  "أم البواقي": "QSF",
  "oum el bouaghi": "QSF",
  "باتنة": "BLJ",
  "batna": "BLJ",
  "خروبة": "BLJ",
  "khenguet": "BLJ",
  "مقرة": "BLJ",
  "merouana": "BLJ",
  "برج الغدير": "BLJ",
  "bir el ater": "BLJ",
  "تبسة": "TEE",
  "tebessa": "TEE",
  "الرقبة": "TEE",
  "ouenza": "TEE",

  // 🇲🇦 المغرب
  "الدار البيضاء": "CMN",
  "casablanca": "CMN",
  "الدارالبيضاء": "CMN",
  "البيضاء": "CMN",
  "الرباط": "RBA",
  "rabat": "RBA",
  "مراكش": "RAK",
  "marrakech": "RAK",
  "فاس": "FEZ",
  "fes": "FEZ",
  "طنجة": "TNG",
  "tanger": "TNG",
  "tanger": "TNG",
  "أغادير": "AGA",
  "اغادير": "AGA",
  "agadir": "AGA",
  "تطوان": "TTU",
  "tetouan": "TTU",
  "وجدة": "OUD",
  "oujda": "OUD",
  "الناظور": "NDR",
  "ناظور": "NDR",
  "nador": "NDR",
  "الحسيمة": "AHU",
  "حسيمة": "AHU",
  "al hoceima": "AHU",
  "بني ملال": "BEM",
  "beni mellal": "BEM",
  "القنيطرة": "NNA",
  "قنيطرة": "NNA",
  "kenitra": "NNA",
  "آسفي": "SFI",
  "اسفي": "SFI",
  "safii": "SFI",
  "الجديدة": "JDA",
  "جديدة": "JDA",
  "el jadida": "JDA",
  "خريبكة": "KHE",
  "khouribga": "KHE",
  "سطات": "CMN",
  "settat": "CMN",
  "برشيد": "CMN",
  "berrechid": "CMN",
  "تمارة": "RBA",
  "temara": "RBA",
  "سلا": "RBA",
  "sale": "RBA",
  "الخميسات": "RBA",
  "khemisset": "RBA",
  "تاوريرت": "OUD",
  "taourirt": "OUD",
  "جرسيف": "OUD",
  "guercif": "OUD",
  "الراشيدية": "ERH",
  "راشيدية": "ERH",
  "errachidia": "ERH",
  "زاكورة": "OZZ",
  "zagora": "OZZ",
  "ورزازات": "OZZ",
  "ouarzazate": "OZZ",
  "تزنيت": "TNG",
  "tiznit": "TNG",
  "تارودانت": "TNG",
  "taroudant": "TNG",
  "شفشاون": "TTU",
  "chefchaouen": "TTU",
  "العرائش": "TNG",
  "larache": "TNG",
  "الصويرة": "ESU",
  "صويرة": "ESU",
  "essaouira": "ESU",
  "الداخلة": "VIL",
  "داخلة": "VIL",
  "dakhla": "VIL",
  "العيون": "EUN",
  "عيون": "EUN",
  "laayoune": "EUN",
  "سمارة": "SMW",
  "smara": "SMW",
  "طانطان": "TNG",
  "tan tan": "TNG",
  "طاطا": "TNG",
  "tata": "TNG",
  "قلعة السراغنة": "RAK",
  "kelaa des sraghna": "RAK",
  "الرحامنة": "RAK",
  "rehamna": "RAK",
  "اليوسفية": "CMN",
  "youssoufia": "CMN",
  "سيدي بنور": "CMN",
  "sidi bennour": "CMN",
  "سيدي إفني": "TNG",
  "sidi ifni": "TNG",
  "إنزكان": "AGA",
  "inzegan": "AGA",
  "أيت ملول": "AGA",
  "ait melloul": "AGA",
  "تارودانت": "TNG",
  "تافراوت": "TNG",
  "tafraout": "TNG",
  "تزنيت": "TNG",
  "أكادير": "AGA",
  "اكادير": "AGA",

  // 🇹🇷 تركيا
  "اسطنبول": "IST",
  "istanbul": "IST",
  "أنقرة": "ESB",
  "انقرة": "ESB",
  "ankara": "ESB",
  "أنطاليا": "AYT",
  "انطاليا": "AYT",
  "antalya": "AYT",
  "إزمير": "ADB",
  "ازمير": "ADB",
  "izmir": "ADB",
  "بودروم": "BJV",
  "bodrum": "BJV",
  "دالaman": "DLM",
  "دالامان": "DLM",
  "dalaman": "DLM",
  "فتحية": "DLM",
  "fethiye": "DLM",
  "طرابزون": "TZX",
  "trabzon": "TZX",
  "بورصة": "YEI",
  "bursa": "YEI",
  "قونية": "KYA",
  "konya": "KYA",
  "غازي عنتاب": "GZT",
  "gaziantep": "GZT",
  "أضنة": "ADA",
  "اضنة": "ADA",
  "adana": "ADA",
  "مرسين": "ADA",
  "mersin": "ADA",
  "تكيرداغ": "TEQ",
  "tekirdag": "TEQ",
  "إسكندرون": "HTY",
  "اسكندرون": "HTY",
  "iskenderun": "HTY",
  "هاتاي": "HTY",
  "hatay": "HTY",
  "سامسون": "SZF",
  "samsun": "SZF",
  "أوردو": "SZF",
  "اوردو": "SZF",
  "ordu": "SZF",
  "جiresun": "SZF",
  "جيرسون": "SZF",
  "giresun": "SZF",
  "ريزة": "RZV",
  "rize": "RZV",
  "أرتفين": "RZV",
  "ارتوين": "RZV",
  "artvin": "RZV",
  "كارس": "KSY",
  "kars": "KSY",
  "أرضروم": "ERZ",
  "ارضروم": "ERZ",
  "erzurum": "ERZ",
  "أغري": "AJI",
  "اغرى": "AJI",
  "agri": "AJI",
  "وان": "VAN",
  "van": "VAN",
  "هكاري": "VAN",
  "hakkari": "VAN",
  "Şırnak": "NKT",
  "شرناق": "NKT",
  "sirnak": "NKT",
  "Siirt": "SXZ",
  "سيرت": "SXZ",
  "siirt": "SXZ",
  "Batman": "BAL",
  "بطمان": "BAL",
  "batman": "BAL",
  "Mardin": "MQM",
  "ماردين": "MQM",
  "mardin": "MQM",
  "Diyarbakır": "DIY",
  "ديار بكر": "DIY",
  "diyarbakir": "DIY",
  "Şanlıurfa": "GNY",
  "Şanlıurfa": "GNY",
  "urfa": "GNY",
  "Adıyaman": "ADF",
  "أديامان": "ADF",
  "adiyaman": "ADF",
  "Malatya": "MLX",
  "ملاطية": "MLX",
  "malatya": "MLX",
  "Elazığ": "EZS",
  "أيلاظغ": "EZS",
  "elazig": "EZS",
  "Bingöl": "BGG",
  "بينغول": "BGG",
  "bingol": "BGG",
  "Muş": "MSR",
  "موش": "MSR",
  "mus": "MSR",
  "Bitlis": "BTL",
  "بتليس": "BTL",
  "bitlis": "BTL",
  "Tunceli": "TUN",
  "تونجeli": "TUN",
  "tunceli": "TUN",
  "Erzincan": "ERC",
  "أرزنجان": "ERC",
  "erzincan": "ERC",
  "Bayburt": "SZF",
  "بايبورت": "SZF",
  "bayburt": "SZF",
  "Gümüşhane": "SZF",
  "غوموشخانه": "SZF",
  "gumushane": "SZF",
  "Çorum": "SZF",
  "تشوروم": "SZF",
  "corum": "SZF",
  "Amasya": "MZH",
  "أماسيا": "MZH",
  "amasya": "MZH",
  "Tokat": "TJK",
  "توقات": "TJK",
  "tokat": "TJK",
  "Nevşehir": "NAV",
  "نفشهير": "NAV",
  "nevsehir": "NAV",
  "Ürgüp": "NAV",
  "أورغوب": "NAV",
  "urgup": "NAV",
  "كابادوكيا": "NAV",
  "cappadocia": "NAV",
  "Aksaray": "NAV",
  "أقسراي": "NAV",
  "aksaray": "NAV",
  "Kırşehir": "NAV",
  "قرشehir": "NAV",
  "kirsehir": "NAV",
  "Yozgat": "ASR",
  "يوزغات": "ASR",
  "yozgat": "ASR",
  "Kırıkkale": "ESB",
  "قرقلkale": "ESB",
  "kirikkale": "ESB",
  "Çankırı": "ESB",
  "تشانكيري": "ESB",
  "cankiri": "ESB",
  "Karabük": "ESB",
  "كارابوك": "ESB",
  "karabuk": "ESB",
  "Bartın": "ESB",
  "بارتين": "ESB",
  "bartin": "ESB",
  "Zonguldak": "ONQ",
  "زونغولداك": "ONQ",
  "zonguldak": "ONQ",
  "Düzce": "ESB",
  "دüzce": "ESB",
  "duzce": "ESB",
  "Bolu": "ESB",
  "بولو": "ESB",
  "bolu": "ESB",
  "Eskişehir": "ESB",
  "أسكي شهر": "ESB",
  "eskisehir": "ESB",
  "Kütahya": "KZR",
  "kutahya": "KZR",
  "Afyonkarahisar": "AFY",
  "أفيون": "AFY",
  "afyon": "AFY",
  "Uşak": "USQ",
  "أوشاك": "USQ",
  "usak": "USQ",
  "Denizli": "DNZ",
  "دنيزلي": "DNZ",
  "denizli": "DNZ",
  "Pamukkale": "DNZ",
  "باموكالى": "DNZ",
  "pamukkale": "DNZ",
  "Muğla": "DLM",
  "موغلا": "DLM",
  "mugla": "DLM",
  "Aydın": "ADB",
  "أيدين": "ADB",
  "aydin": "ADB",
  "Manisa": "ADB",
  "مانيسا": "ADB",
  "manisa": "ADB",
  "Balıkesir": "BZI",
  "باليكسير": "BZI",
  "balikesir": "BZI",
  "Çanakkale": "CKZ",
  "تشاناكkale": "CKZ",
  "canakkale": "CKZ",
  "Edirne": "EDO",
  "أدرنة": "EDO",
  "edirne": "EDO",
  "Kırklareli": "EDO",
  "كركلareli": "EDO",
  "kirklareli": "EDO",
  "Sakarya": "ESB",
  "سكاريا": "ESB",
  "sakarya": "ESB",
  "Kocaeli": "ESB",
  "كوجaeli": "ESB",
  "kocaeli": "ESB",
  "Yalova": "YAL",
  "يالوفا": "YAL",
  "yalova": "YAL",
  "Bilecik": "ESB",
  "بيليجيك": "ESB",
  "bilecik": "ESB",
  "Karaman": "KYA",
  "كرمان": "KYA",
  "karaman": "KYA",
  "Konya": "KYA",
  "Mersin": "ADA",
  "Osmaniye": "ADA",
  "osmaniye": "ADA",
  "Kahramanmaraş": "KCM",
  "قهرمان مرعش": "KCM",
  "kahramanmaras": "KCM",
  "Kilis": "GZT",
  "كيليس": "GZT",
  "kilis": "GZT",

  // 🇬🇧 بريطانيا
  "لندن": "LHR",
  "london": "LHR",
  "مانشستر": "MAN",
  "manchester": "MAN",
  "برمنغهام": "BHX",
  "برمنجهام": "BHX",
  "birmingham": "BHX",
  "إدنبره": "EDI",
  "ادنبره": "EDI",
  "edinburgh": "EDI",
  "غلاسكو": "GLA",
  "glasgow": "GLA",
  "نيوكاسل": "NCL",
  "newcastle": "NCL",
  "ليفربول": "LPL",
  "liverpool": "LPL",
  "بريستول": "BRS",
  "bristol": "BRS",
  "بلفاست": "BFS",
  "belfast": "BFS",
  "كارديف": "CWL",
  "cardiff": "CWL",

  // 🇫🇷 فرنسا
  "باريس": "CDG",
  "paris": "CDG",
  "مرسيليا": "MRS",
  "marseille": "MRS",
  "ليون": "LYS",
  "lyon": "LYS",
  "نيس": "NCE",
  "nice": "NCE",
  "تولوز": "TLS",
  "toulouse": "TLS",
  "بوردو": "BOD",
  "bordeaux": "BOD",
  "ستراسبورغ": "SXB",
  "strasbourg": "SXB",
  "نانت": "NTE",
  "nantes": "NTE",
  "ليل": "LIL",
  "lille": "LIL",
  "مونبلييه": "MPL",
  "montpellier": "MPL",
  "رين": "RNS",
  "rennes": "RNS",
  "روما": "FCO",
  "rome": "FCO",
  "ميلان": "MXP",
  "milan": "MXP",
  "البندقية": "VCE",
  "بندقية": "VCE",
  "venice": "VCE",
  "نابولي": "NAP",
  "naples": "NAP",
  "تورينو": "TRN",
  "turin": "TRN",
  "فلورنسا": "FLR",
  "florence": "FLR",
  "بولونيا": "BLQ",
  "bologna": "BLQ",
  "كاتانيا": "CTA",
  "catania": "CTA",
  "باري": "BRI",
  "bari": "BRI",
  "بيزا": "PSA",
  "pisa": "PSA",
  "جنوة": "GOA",
  "genoa": "GOA",
  "بيرغامو": "BGY",
  "bergamo": "BGY",
  "فيرونا": "VRN",
  "verona": "VRN",
  "بادوفا": "VRN",
  "padova": "VRN",
  "فيتشنزا": "VRN",
  "vicenza": "VRN",
  "تريفيزو": "VRN",
  "treviso": "VRN",
  "أوديني": "UDN",
  "udine": "UDN",
  "ترييستي": "TRS",
  "trieste": "TRS",
  "بولتسانو": "BZO",
  "bolzano": "BZO",
  "تيرنتو": "BZO",
  "trento": "BZO",
  "مودينا": "BLQ",
  "modena": "BLQ",
  "بارما": "BLQ",
  "parma": "BLQ",
  "ريدجو إميليا": "BLQ",
  "reggio emilia": "BLQ",
  "فورلي": "FRL",
  "forli": "FRL",
  "ريميني": "RMI",
  "rimini": "RMI",
  "أنكونا": "AOI",
  "ancona": "AOI",
  "بيسكارا": "PSR",
  "pescara": "PSR",
  "كييتي": "PSR",
  "chieti": "PSR",
  "كامبوباسو": "PSR",
  "campobasso": "PSR",
  "فوجيا": "BRI",
  "foggia": "BRI",
  "ليتشي": "BRI",
  "lecce": "BRI",
  "برينديزي": "BDS",
  "brindisi": "BDS",
  "تارانتو": "BDS",
  "taranto": "BDS",
  "ماتيرا": "BDS",
  "matera": "BDS",
  "بوتنسا": "BDS",
  "potenza": "BDS",
  "كالابريا": "SUF",
  "calabria": "SUF",
  "كوزنسا": "SUF",
  "cosenza": "SUF",
  "كاتانزارو": "SUF",
  "catanzaro": "SUF",
  "ريدجو كالابريا": "REG",
  "reggio calabria": "REG",
  "مسينة": "CTA",
  "messina": "CTA",
  "باليرمو": "PMO",
  "palermo": "PMO",
  "كالياري": "CAG",
  "cagliari": "CAG",
  "ساساري": "AHO",
  "sassari": "AHO",
  "أولبيا": "OLB",
  "olbia": "OLB",
  "ألغيرو": "AHO",
  "alghero": "AHO",
  "كالياري": "CAG",
  "كوارتوسانتيلينا": "CAG",
  "quartu santelena": "CAG",
  "أوريستانو": "CAG",
  "oristano": "CAG",
  "نورو": "CAG",
  "nuoro": "CAG",
  "أوبيا": "OLB",
  "tempio pausania": "OLB",
  "أولبيا تمبيو": "OLB",
  "olbia tempio": "OLB",
  "ساساري": "AHO",
  "سردينيا": "CAG",
  "sardinia": "CAG",
  "صقلية": "CTA",
  "sicily": "CTA",
  "إلبا": "EBA",
  "elba": "EBA",
  "كابري": "NAP",
  "capri": "NAP",
  "إسكيا": "NAP",
  "ischia": "NAP",
  "بروكيدا": "NAP",
  "procida": "NAP",
  "بونزا": "NAP",
  "ponza": "NAP",
  "فنتوتيني": "NAP",
  "ventotene": "NAP",
  "سانريمو": "NCE",
  "sanremo": "NCE",
  "بورديغيرا": "NCE",
  "bordighera": "NCE",
  "ألبينجا": "NCE",
  "albenga": "NCE",
  "إمبيريا": "NCE",
  "imperia": "NCE",
  "سافونا": "GOA",
  "savona": "GOA",
  "سانتا مارغريتا": "GOA",
  "santa margherita": "GOA",
  "بورتوفينيري": "GOA",
  "portofino": "GOA",
  "رابالو": "GOA",
  "rapallo": "GOA",
  "تشينكوي تيري": "GOA",
  "cinque terre": "GOA",
  "فياريدجيو": "GOA",
  "viareggio": "GOA",
  "مونتيكاتيني": "FLR",
  "montecatini": "FLR",
  "سيينا": "FLR",
  "siena": "FLR",
  "أريكيا": "FLR",
  "arezzo": "FLR",
  "بيروجيا": "FLR",
  "perugia": "FLR",
  "أورفيتو": "FLR",
  "orvieto": "FLR",
  "أسيزي": "FLR",
  "assisi": "FLR",
  "سبوليتو": "FLR",
  "spoleto": "FLR",
  "تودي": "FLR",
  "todi": "FLR",
  "جوبيو": "FLR",
  "gubbio": "FLR",
  "كورتونا": "FLR",
  "cortona": "FLR",
  "سان جيمينيانو": "FLR",
  "san gimignano": "FLR",
  "فولتيرا": "FLR",
  "volterra": "FLR",
  "بيزا": "PSA",
  "ليفورنو": "PSA",
  "livorno": "PSA",
  "لوكا": "PSA",
  "lucca": "PSA",
  "بيستويا": "PSA",
  "pistoia": "PSA",
  "براتو": "PSA",
  "prato": "PSA",
  "كارارا": "PSA",
  "carrara": "PSA",
  "ماسا": "PSA",
  "massa": "PSA",
  "فياريدجيو": "PSA",
  "بيترasanti": "PSA",
  "pietrasanta": "PSA",
  "كامايوري": "PSA",
  "camaiore": "PSA",
  "فورتي دي مارمي": "PSA",
  "forte dei marmi": "PSA",
  "مونتيكاتيني": "PSA",
  "مونتيكاتيني تيرمي": "PSA",
  "montecatini terme": "PSA",
  "فينيشيا": "VCE",
  "فينيسيا": "VCE",
  "venezia": "VCE",
  "بادوفا": "VCE",
  "فيرونا": "VCE",
  "فيتشنزا": "VCE",
  "تريفيزو": "VCE",
  "كورتينا دامبيتس": "VCE",
  "cortina dampezzo": "VCE",
  "دولوميتي": "VCE",
  "dolomiti": "VCE",
  "ليكو": "MXP",
  "lecco": "MXP",
  "كومو": "MXP",
  "como": "MXP",
  "فاريزي": "MXP",
  "varese": "MXP",
  "نوفارا": "MXP",
  "novara": "MXP",
  "بييلا": "MXP",
  "biella": "MXP",
  "فيرشيلي": "MXP",
  "vercelli": "MXP",
  "أليساندريا": "MXP",
  "alessandria": "MXP",
  "أستي": "MXP",
  "asti": "MXP",
  "كيونيو": "MXP",
  "cuneo": "MXP",
  "تورينو": "TRN",
  "أوستا": "TRN",
  "aosta": "TRN",
  "فال دا أوستا": "TRN",
  "val daosta": "TRN",
  "كورمايور": "TRN",
  "courmayeur": "TRN",
  "بريلا": "TRN",
  "breuil cervinia": "TRN",
  "سستريير": "TRN",
  "sestriere": "TRN",
  "ساوز دولكس": "TRN",
  "sauze doulx": "TRN",
  "باري": "BRI",
  "تارانتو": "BDS",
  "برينديزي": "BDS",
  "ليتشي": "BRI",
  "أوترانتو": "BRI",
  "otranto": "BRI",
  "غاليبولي": "BRI",
  "gallipoli": "BRI",
  "ألتامورا": "BRI",
  "altamura": "BRI",
  "ماتيرا": "BRI",
  "تراني": "BRI",
  "trani": "BRI",
  "بارييتا": "BRI",
  "barletta": "BRI",
  "أندريا": "BRI",
    // 🇺🇸 أمريكا — أكمل
  "نيويورك": "JFK", "نيو يورك": "JFK", "new york": "JFK",
  "newyork": "JFK",
  "nyc": "JFK",
  "لوس أنجلوس": "LAX", "los angeles": "LAX", "losangeles": "LAX",
  "ميامي": "MIA", "miami": "MIA",
  "شيكاغو": "ORD", "chicago": "ORD",
  "سان فرانسيسكو": "SFO", "san francisco": "SFO", "sanfrancisco": "SFO",
  "واشنطن": "DCA", "washington": "DCA",
  "لاس فيغاس": "LAS", "las vegas": "LAS", "lasvegas": "LAS",
  "هونولولو": "HNL", "honolulu": "HNL",
  "بوسطن": "BOS", "boston": "BOS",
  "سياتل": "SEA", "seattle": "SEA",
  "دنفر": "DEN", "denver": "DEN",
  "أتلانتا": "ATL", "atlanta": "ATL",
  "دالاس": "DFW", "dallas": "DFW",
  "فيلادلفيا": "PHL", "philadelphia": "PHL",
  "هيوستن": "IAH", "houston": "IAH",
  "فينيكس": "PHX", "phoenix": "PHX",
  "سان دييغو": "SAN", "san diego": "SAN", "sandiego": "SAN",
  "أورلاندو": "MCO", "orlando": "MCO",
  "سان خوسيه": "SJC", "san jose": "SJC", "sanjose": "SJC",
  "أوستن": "AUS", "austin": "AUS",
  "ناشفيل": "BNA", "nashville": "BNA",
  "بورتلاند": "PDX", "portland": "PDX",
  "ديترويت": "DTW", "detroit": "DTW",
  "منيابولس": "MSP", "minneapolis": "MSP",
  "كليفلاند": "CLE", "cleveland": "CLE",
  "سانت لويس": "STL", "saint louis": "STL", "st louis": "STL",
  "تامبا": "TPA", "tampa": "TPA",
  "شارلوت": "CLT", "charlotte": "CLT",
  "بالتيمور": "BWI", "baltimore": "BWI",
  "سان أنطونيو": "SAT", "san antonio": "SAT", "sanantonio": "SAT",
  "إنديانابوليس": "IND", "indianapolis": "IND",
  "كولومبوس": "CMH", "columbus": "CMH",
  "ساكرامنتو": "SMF", "sacramento": "SMF",
  "كانساس سيتي": "MCI", "kansas city": "MCI", "kansascity": "MCI",
  "أوكلاهوما سيتي": "OKC", "oklahoma city": "OKC", "oklahomacity": "OKC",
  "نيو أورلينز": "MSY", "new orleans": "MSY", "neworleans": "MSY",
  "ميلووكي": "MKE", "milwaukee": "MKE",
  "ألباكركي": "ABQ", "albuquerque": "ABQ",
  "توسون": "TUS", "tucson": "TUS",
  "أوكلاند": "OAK", "oakland": "OAK",
  "ريتشموند": "RIC", "richmond": "RIC",
  "نيوارك": "EWR", "newark": "EWR",
  "جاكسونفيل": "JAX", "jacksonville": "JAX",
  "رالي": "RDU", "raleigh": "RDU",
  "سولت ليك سيتي": "SLC", "salt lake city": "SLC", "saltlakecity": "SLC",
  "هارتفورد": "BDL", "hartford": "BDL",
  "بافالو": "BUF", "buffalo": "BUF",
  "ممفيس": "MEM", "memphis": "MEM",
  "أوماها": "OMA", "omaha": "OMA",
  "هونولولو": "HNL",
  "كاهولوي": "OGG", "kahului": "OGG",
  "كايلوا": "KOA", "kailua": "KOA",
  "ليهو": "LIH", "lihue": "LIH",
  "مولوكاي": "MKK", "molokai": "MKK",
  "لاناي": "LNY", "lanai": "LNY",
};

export function getCityName(iataCode: string): string {
  return iataToCityName[iataCode.toUpperCase()] || iataCode;
}

export function getIataCode(cityName: string): string {
  // Try Arabic first
  const normalized = cityName.trim().toLowerCase();
  if (arabicToIata[normalized]) {
    return arabicToIata[normalized];
  }
  
  // Try English (reverse lookup)
  const entries = Object.entries(iataToCityName);
  const found = entries.find(([, name]) => name.toLowerCase() === normalized);
  if (found) return found[0];
  
  // Return as-is if it's already an IATA code
  if (/^[A-Z]{3}$/i.test(normalized)) {
    return normalized.toUpperCase();
  }
  
  return cityName;
}